//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.KeToan.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.KeToan.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT_FOUND_DATA.
        /// </summary>
        public static string DevMsg_DataNotFound {
            get {
                return ResourceManager.GetString("DevMsg_DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate code.
        /// </summary>
        public static string DevMsg_DuplicateCode {
            get {
                return ResourceManager.GetString("DevMsg_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catched an exception..
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_MISSING_INPUT.
        /// </summary>
        public static string DevMsg_MissingInput {
            get {
                return ResourceManager.GetString("DevMsg_MissingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_WRONG_INPUT.
        /// </summary>
        public static string DevMsg_WrongInput {
            get {
                return ResourceManager.GetString("DevMsg_WrongInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy đổi mã sang mã chưa tồn tại trong dữ liệu.
        /// </summary>
        public static string MoreInfo_DuplicateCode {
            get {
                return ResourceManager.GetString("MoreInfo_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thêm.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại dữ liệu.
        /// </summary>
        public static string UserMsg_DataNotFound {
            get {
                return ResourceManager.GetString("UserMsg_DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng mã.
        /// </summary>
        public static string UserMsg_DuplicateCode {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ với Misa.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập thiếu trường.
        /// </summary>
        public static string UserMsg_MissingInput {
            get {
                return ResourceManager.GetString("UserMsg_MissingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập sai định dạng.
        /// </summary>
        public static string UserMsg_WrongInput {
            get {
                return ResourceManager.GetString("UserMsg_WrongInput", resourceCulture);
            }
        }
    }
}
